2008-07-03 16:48 UTC+0200 Viktor Szakats (harbour.01 syenar hu)    * contrib/hbmzip/hbmzip.c      + Added ".cmd" to the (commented) list of OS/2 executable        extensions.      + Added headers for DOS/GCC line.      + Guarded new DOS section with GCC guards, added dummy        branch for other DOS compilers.      ! Fixed embedded comment.      ; TOFIX:        ../../hbmzip.c:563: error: 'FILE_ATTRIBUTE_READONLY' undeclared (first use in this function)        ../../hbmzip.c:568: error: 'FILE_ATTRIBUTE_DIRECTORY' undeclared (first use in this function)
   * contrib/hbmisc/spd.c
     - Removed two __XHARBOUR__ guards, because these feature 
       have since been implemented in xhb.
     ! Fixed DJGPP warning. The problem is that DJGPP will preprocess 
       snprintf() to sprintf() (not very safe), which makes ulMaxBuf 
       var unused.


git-svn-id: https://harbour-project.svn.sourceforge.net/svnroot/harbour-project/trunk@8922 ef52b332-12a4-b543-bf59-08b57769829b