2008-05-29 17:02 UTC+0100 Viktor Szakats (harbour.01 syenar hu)    * source/rtl/tget.prg      * ::picture(), ::PutMask(), ::unTransform() moved next        to each other for easier editing/fixing.
   * common.mak
   - source/common/hbfhnd.c
   * source/common/Makefile
     - Removed file not used by Harbour anymore.

   * contrib/hbole/ole2.c
     ! Fixed OLE C++ errors under MSVC. Using Przemek's method.
     ; TOFIX: This one is still left:
        .\ole2.c(714) : error C2664: 'HRESULT (IUnknown *,const IID &,void **)' : cannot convert parameter 2 from 'LPIID' to 'const IID &'
            Reason: cannot convert from 'LPIID' to 'const IID'
            No constructor could take the source type, or constructor overload resolution was ambiguous


git-svn-id: https://harbour-project.svn.sourceforge.net/svnroot/harbour-project/trunk@8520 ef52b332-12a4-b543-bf59-08b57769829b